import { ArrowUpRight, BookOpen, MessageSquare, Link2, Activity } from "lucide-react";
import type { PostRecord, TaskRecord } from "../../shared/contracts";
import { statusLabel, type Comment, type Friend } from "../lib/types";
import { useData } from "../lib/use-data";
import { PageHeader, Notice, Badge, Loading, Empty, Reload } from "../components/Common";
import { timestamp } from "../lib/api";
export function Dashboard() {
	const posts = useData<PostRecord[]>("/posts"); const comments = useData<Comment[]>("/comments"); const friends = useData<Friend[]>("/friends"); const tasks = useData<TaskRecord[]>("/tasks");
	const pending = friends.data?.filter(friend => friend.status === "pending").length;
	const failed = tasks.data?.filter(task => ["failed", "conflict", "unknown"].includes(task.state)).length;
	const latest = tasks.data?.[0];
	const metrics = [ { label: "管理文章", value: posts.data?.length, icon: BookOpen, detail: posts.data ? `${posts.data.filter(post => !post.draft).length} 篇非草稿 · ${posts.data.filter(post => post.draft).length} 篇草稿` : "读取内容记录", href: "posts" }, { label: "评论", value: comments.data?.length, icon: MessageSquare, detail: "公开互动与回复", href: "comments" }, { label: "待审核友链", value: pending, icon: Link2, detail: "审核后随显式发布上线", href: "friends" }, { label: "需处理任务", value: failed, icon: Activity, detail: "失败、冲突及结果未知", href: "releases" } ];
	return <><PageHeader title="仪表盘" subtitle="把内容写好，让每一次发布有据可查。" action={<Reload onClick={() => { void posts.reload(); void comments.reload(); void friends.reload(); void tasks.reload(); }}/>}/>{[posts.error, comments.error, friends.error, tasks.error].filter(Boolean).map((error, index) => <Notice key={index}>{error}</Notice>)}<div className="metric-grid">{metrics.map(metric => <a key={metric.label} className="metric-card" href={`#${metric.href}`}><div><span>{metric.label}</span><metric.icon size={19}/></div><strong>{metric.value ?? "—"}</strong><small>{metric.detail}</small><ArrowUpRight className="metric-arrow" size={16}/></a>)}</div><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><h2>最近编辑</h2><a href="#posts">所有文章 ↗</a></div>{posts.loading ? <Loading/> : posts.data?.length ? <div className="row-list">{posts.data.slice(0, 5).map(post => <a key={post.id} href={`#posts?post=${encodeURIComponent(post.id)}`} className="list-row"><div><strong>{post.title || "未命名文章"}</strong><small>{post.slug} · {timestamp(post.updatedAt)}</small></div><Badge tone={post.draft ? "neutral" : "green"}>{post.draft ? "草稿" : post.publishedRevision === post.revision ? "已上线" : "待发布"}</Badge></a>)}</div> : <Empty>暂无文章。先导入现有仓库基线或创建私有草稿。</Empty>}</section><section className="panel"><div className="panel-heading"><h2>最近发布</h2><a href="#releases">查看任务 ↗</a></div>{tasks.loading ? <Loading/> : latest ? <div className="release-summary"><Badge tone={latest.state === "verified" ? "green" : "neutral"}>{statusLabel(latest.state)}</Badge><p>{latest.message || "发布状态来自持久任务"}</p><dl><dt>目标 Git SHA</dt><dd><code>{latest.targetSha || "尚未提交"}</code></dd><dt>生产 Git SHA</dt><dd><code>{latest.productionSha || "尚未核验"}</code></dd><dt>最近检查</dt><dd>{timestamp(latest.updatedAt)}</dd></dl></div> : <Empty>还没有发布任务。</Empty>}<div className="panel-note">生产上线同时核对 Git 目标版本、域名当前指向及内容清单。</div></section><section className="panel"><div className="panel-heading"><h2>最新评论</h2><a href="#comments">管理评论 ↗</a></div>{comments.loading ? <Loading/> : comments.data?.length ? comments.data.slice(0, 4).map(comment => <div className="comment-preview" key={comment.id}><strong>{comment.name || "访客"}</strong><p>{comment.body}</p><small>{timestamp(comment.createdAt)}</small></div>) : <Empty>暂无评论。</Empty>}</section><section className="panel welcome-panel"><p className="eyebrow">YOUR PUBLISHING DESK</p><h2>先保存，再发布。</h2><p>保存只更新私有草稿。发布时冻结快照，期间继续编辑不会改变正在部署的内容。</p><div className="actions"><a className="button" href="#posts">开始写作 <ArrowUpRight size={16}/></a><a className="button secondary" href="#maintenance">查看备份</a></div></section></div></>;
}
