import { useEffect, useRef, useState } from "react";
import { ArrowDown, ArrowUp, Plus, Save, Trash2, Upload } from "lucide-react";
import type { MediaRecord } from "../../shared/contracts";
import { useData } from "../lib/use-data";
import { write } from "../lib/api";
import { uploadMedia } from "../lib/upload";
import { ActionStatus, Empty, Field, Loading, Notice, PageHeader, useAction, useUnsavedChanges } from "../components/Common";
type NavLink = { name: string; url: string; icon?: string; external?: boolean; pageKey?: string; children?: NavLink[] };
const slots = ["favicon.svg", "favicon.ico", "favicon-96x96.png", "apple-touch-icon.png", "web-app-manifest-192x192.png", "web-app-manifest-512x512.png"] as const;
export function Navigation() {
	const navigation = useData<{ links: NavLink[] }>("/navigation"); const settings = useData<Record<string, string>>("/icons"); const media = useData<MediaRecord[]>("/media"); const action = useAction(); const [links, setLinks] = useState<NavLink[]>([]); const [icons, setIcons] = useState<Record<string, string>>({}); const [uploadSlot, setUploadSlot] = useState<string | null>(null); const [uploadInfo, setUploadInfo] = useState(""); const fileInput = useRef<HTMLInputElement>(null);
	useEffect(() => { if (navigation.data) setLinks(navigation.data.links ?? []); }, [navigation.data]);
	useEffect(() => { if (settings.data) setIcons(settings.data); }, [settings.data]);
	useUnsavedChanges(Boolean(navigation.data && JSON.stringify(links) !== JSON.stringify(navigation.data.links ?? []) || settings.data && JSON.stringify(icons) !== JSON.stringify(settings.data)));
	async function saveNavigation() { await write("/navigation", { data: { ...navigation.data, links }, expectedRevision: navigation.revision }, "PUT"); await navigation.reload(); }
	async function uploadFiles(files: FileList | null) { if (!files?.length) return; await action.run(async () => { const entries = Array.from(files); let imported = 0; const missing: string[] = []; const next = { ...icons }; for (const file of entries) { const matched = uploadSlot ?? slots.find(slot => slot.toLowerCase() === file.name.toLowerCase()); if (!matched) { missing.push(file.name); continue; } const uploaded = await uploadMedia(file); next[matched] = `media:${uploaded.id}`; imported++; } setIcons(next); await media.reload(); setUploadInfo(`${imported} 个图标已直传，核验后可保存图标绑定。${missing.length ? ` 未识别并跳过：${missing.join("、")}` : ""}`); }); if (fileInput.current) fileInput.current.value = ""; setUploadSlot(null); }
	return <><PageHeader title="导航与图标" subtitle="编辑现有分组与二级菜单，保留主题导航样式和页面结构。" action={<button className="button" disabled={action.busy || !navigation.data} onClick={() => void action.run(saveNavigation, "导航已保存为私有草稿，等待显式发布。") }><Save size={16}/>保存导航草稿</button>}/><ActionStatus action={action}/>{navigation.error && <Notice>{navigation.error}</Notice>}{settings.error && <Notice>{settings.error}</Notice>}<section className="panel form-panel"><div className="panel-heading"><h2>菜单与分组</h2><button className="button secondary" onClick={() => setLinks([...links, { name: "新菜单", url: "", icon: "" }])}><Plus size={16}/>添加一级菜单</button></div>{navigation.loading ? <Loading/> : links.length ? <NavList links={links} onChange={setLinks}/> : <Empty>暂无导航配置，请先导入仓库基线。</Empty>}<div className="panel-note">一级菜单的地址可留空作为分组，添加子菜单后形成二级导航。上下按钮改变实际顺序。</div></section><section className="panel form-panel icons-panel"><div className="panel-heading"><div><h2>六个网站图标位</h2><p>按原始文件名识别，保留文件格式，不自动转换。</p></div><button className="button secondary" disabled={action.busy} onClick={() => { setUploadSlot(null); fileInput.current?.click(); }}><Upload size={16}/>批量导入图标包</button></div><input hidden ref={fileInput} type="file" accept=".svg,.ico,.png" multiple onChange={event => void uploadFiles(event.target.files)}/>{uploadInfo && <Notice success>{uploadInfo}</Notice>}<div className="icon-slots">{slots.map(slot => <div className="icon-slot" key={slot}><code>{slot}</code><input aria-label={`${slot}媒体引用`} value={icons[slot] ?? ""} list="icon-media-options" placeholder="未覆盖现有图标" onChange={event => setIcons({ ...icons, [slot]: event.target.value })}/><button className="button secondary" disabled={action.busy} onClick={() => { setUploadSlot(slot); fileInput.current?.click(); }}>选择原始文件</button></div>)}</div><datalist id="icon-media-options">{media.data?.filter(item => /image|icon/.test(item.contentType)).map(item => <option key={item.id} value={`media:${item.id}`}>{item.name}</option>)}</datalist><p className="panel-note">批量导入选择图标包中的多个原始文件，按六个规范文件名匹配。ZIP 压缩包请先解压。空图标位沿用现有资源。</p><button className="button" disabled={action.busy || !settings.data} onClick={() => void action.run(async () => { const savedIcons = Object.fromEntries(Object.entries(icons).filter(([, value]) => value)); await write("/icons", { data: savedIcons, expectedRevision: settings.revision }, "PUT"); await settings.reload(); }, "图标绑定已保存为私有草稿。发布时才更新网站图标。")}>保存图标绑定</button></section></>;
}
function NavList({ links, onChange, depth = 0 }: { links: NavLink[]; onChange: (links: NavLink[]) => void; depth?: number }) {
	function update(index: number, patch: Partial<NavLink>) { onChange(links.map((link, position) => index === position ? { ...link, ...patch } : link)); }
	function move(index: number, direction: number) { const next = [...links]; const other = index + direction; if (other < 0 || other >= links.length) return; [next[index], next[other]] = [next[other], next[index]]; onChange(next); }
	return <div className={`nav-edit-list level-${depth}`}>{links.map((link, index) => <div className="nav-edit-item" key={index}><div className="nav-edit-row"><span className="sort-number">{index + 1}</span><Field label="名称"><input value={link.name} onChange={event => update(index, { name: event.target.value })}/></Field><Field label="地址"><input value={link.url} onChange={event => update(index, { url: event.target.value })}/></Field><Field label="图标"><input value={link.icon ?? ""} placeholder="fa7-solid:house" onChange={event => update(index, { icon: event.target.value })}/></Field><label className="check-field compact"><input type="checkbox" checked={link.external ?? false} onChange={event => update(index, { external: event.target.checked })}/>外链</label><div className="actions"><button className="icon-button" aria-label={`上移${link.name}`} disabled={index === 0} onClick={() => move(index, -1)}><ArrowUp size={16}/></button><button className="icon-button" aria-label={`下移${link.name}`} disabled={index === links.length - 1} onClick={() => move(index, 1)}><ArrowDown size={16}/></button><button className="icon-button danger" aria-label={`删除${link.name}`} onClick={() => onChange(links.filter((_, position) => position !== index))}><Trash2 size={16}/></button></div></div>{link.children?.length ? <NavList depth={depth + 1} links={link.children} onChange={children => update(index, { children })}/> : null}{depth === 0 && <button className="text-button add-child" onClick={() => update(index, { children: [...(link.children ?? []), { name: "子菜单", url: "" }] })}><Plus size={14}/>添加二级菜单</button>}</div>)}</div>;
}
