import { useEffect, useState } from "react";
import { Save, Plus, Trash2 } from "lucide-react";
import type { MediaRecord } from "../../shared/contracts";
import { write } from "../lib/api";
import { useData } from "../lib/use-data";
import { ActionStatus, Field, Loading, Notice, PageHeader, useAction, useUnsavedChanges } from "../components/Common";
type Contact = { name: string; url: string; icon?: string; showName?: boolean };
type SettingsData = Record<string, unknown> & { contactLinks?: Contact[] };
export function Settings() {
	const settings = useData<SettingsData>("/settings"); const media = useData<MediaRecord[]>("/media"); const action = useAction(); const [data, setData] = useState<SettingsData>({});
	useEffect(() => { if (settings.data) setData(settings.data); }, [settings.data]);
	useUnsavedChanges(Boolean(settings.data && JSON.stringify(data) !== JSON.stringify(settings.data)));
	function field(key: string, label: string, hint?: string, multiline = false) { return <Field key={key} label={label} hint={hint}>{multiline ? <textarea rows={3} value={String(data[key] ?? "")} onChange={event => setData({ ...data, [key]: event.target.value })}/> : <input value={String(data[key] ?? "")} onChange={event => setData({ ...data, [key]: event.target.value })}/>}</Field>; }
	async function save() { await write("/settings", { data, expectedRevision: settings.revision }, "PUT"); await settings.reload(); }
	return <><PageHeader title="站点设置" subtitle="保留主题布局、功能开关与未纳入管理的配置，只编辑约定字段。" action={<button className="button" disabled={action.busy || settings.loading || !settings.data} onClick={() => void action.run(save, "站点设置已保存为私有草稿。请在发布任务中显式发布。") }><Save size={16}/>保存设置草稿</button>}/><ActionStatus action={action}/>{settings.error && <Notice>{settings.error}</Notice>}{settings.loading ? <Loading/> : settings.data && <div className="settings-grid"><section className="panel form-panel"><h2>站点身份</h2>{field("title", "站点标题")}{field("subtitle", "站点副标题")}{field("description", "站点描述", undefined, true)}{field("siteUrl", "网站规范地址", "包含 https:// 和末尾斜杠。")}{field("timezone", "时区")}{field("siteStartDate", "建站时间", "显式携带时区，例如 2026-07-26T00:00:00+08:00。")}</section><section className="panel form-panel"><h2>作者资料</h2>{field("profileName", "显示名称")}{field("bio", "两行签名", "保留原文字、空格与换行。", true)}<AssetField label="头像" value={data.avatar} onChange={value => setData({ ...data, avatar: value })} media={media.data ?? []}/><div className="panel-note">头像和默认图标应使用原始来源文件；原图未提供时保留现有资源。</div></section><section className="panel form-panel"><h2>首页与背景</h2><AssetField label="首页封面" value={data.homeCover} onChange={value => setData({ ...data, homeCover: value })} media={media.data ?? []} responsive/><AssetField label="默认文章封面" value={data.defaultCover} onChange={value => setData({ ...data, defaultCover: value })} media={media.data ?? []}/><AssetField label="背景" value={data.background} onChange={value => setData({ ...data, background: value })} media={media.data ?? []} responsive/><div className="panel-note">媒体引用在显式发布时转换为公开不可变版本。主题开关和动画速度沿用现有配置。</div></section><section className="panel form-panel"><div className="panel-heading"><h2>联系方式</h2><button className="text-button" onClick={() => setData({ ...data, contactLinks: [...(data.contactLinks ?? []), { name: "", url: "", icon: "" }] })}><Plus size={15}/>添加</button></div>{data.contactLinks?.map((contact, index) => <div className="contact-editor" key={index}><Field label="名称"><input value={contact.name} onChange={event => { const links = [...(data.contactLinks ?? [])]; links[index] = { ...contact, name: event.target.value }; setData({ ...data, contactLinks: links }); }}/></Field><Field label="地址"><input value={contact.url} onChange={event => { const links = [...(data.contactLinks ?? [])]; links[index] = { ...contact, url: event.target.value }; setData({ ...data, contactLinks: links }); }}/></Field><Field label="主题图标"><input value={contact.icon ?? ""} onChange={event => { const links = [...(data.contactLinks ?? [])]; links[index] = { ...contact, icon: event.target.value }; setData({ ...data, contactLinks: links }); }}/></Field><button className="icon-button danger" aria-label={`删除联系方式${contact.name}`} onClick={() => setData({ ...data, contactLinks: data.contactLinks?.filter((_, position) => position !== index) })}><Trash2 size={17}/></button></div>)}</section></div>}</>;
}
export function AssetField({ label, value, onChange, media, responsive = false }: { label: string; value: unknown; onChange: (value: unknown) => void; media: MediaRecord[]; responsive?: boolean }) {
	const assets = media.filter(item => item.contentType.startsWith("image/")); const structured = value && typeof value === "object" && !Array.isArray(value) ? value as { desktop?: string | string[]; mobile?: string | string[] } : null;
	const id = `asset-${label.replace(/\s/g, "")}`;
	function input(current: string | string[] | undefined, change: (value: string | string[]) => void, subtitle: string) { const multiple = Array.isArray(current); return <Field label={subtitle} hint="可填写相对路径、HTTPS 外链或选择私有媒体引用。">{multiple ? <textarea rows={4} value={current.join("\n")} onChange={event => change(event.target.value.split("\n"))}/> : <input list={id} value={current ?? ""} onChange={event => change(event.target.value)}/>}{multiple && <small>每行一个图片地址，保留实际列表与顺序。</small>}</Field>; }
	return <div className="asset-field">{structured ? <>{input(structured.desktop, next => onChange({ ...structured, desktop: next }), `${label} · 桌面`)}{input(structured.mobile, next => onChange({ ...structured, mobile: next }), `${label} · 移动`)}</> : input(typeof value === "string" ? value : "", onChange, label)}{responsive && !structured && <button className="text-button" type="button" onClick={() => onChange({ desktop: typeof value === "string" ? value : "", mobile: typeof value === "string" ? value : "" })}>分别设置桌面与移动资源</button>}<datalist id={id}>{assets.map(item => <option key={item.id} value={`media:${item.id}`}>{item.name}</option>)}</datalist></div>;
}
