type Operation = Record<string, unknown>;
const jsonResponse = { description: "JSON result", content: { "application/json": { schema: { type: "object", additionalProperties: true } } } };
const security = [{ session: [], csrf: [] }];
const paths: Record<string, Record<string, Operation>> = {};
function route(method: string, path: string, tag: string, summary: string, publicAccess = false, fields?: Record<string, unknown>, required: string[] = []) {
	const operation: Operation = { tags: [tag], summary, security: publicAccess ? [] : method === "get" ? [{ session: [] }] : security, responses: { "200": jsonResponse, "201": jsonResponse, "202": jsonResponse, "400": jsonResponse, "401": jsonResponse, "403": jsonResponse, "409": jsonResponse, "503": jsonResponse } };
	const parameters = [...path.matchAll(/\{([^}]+)\}/g)].map((match) => ({ name: match[1], in: "path", required: true, schema: { type: "string" } }));
	if (path === "/api/public/comments" && method === "get") parameters.push({ name: "articleId", in: "query", required: true, schema: { type: "string" } });
	if (parameters.length) operation.parameters = parameters;
	if (fields) operation.requestBody = { required: true, content: { "application/json": { schema: { type: "object", properties: fields, required, additionalProperties: true } } } };
	(paths[path] ||= {})[method] = operation;
}
const string = { type: "string" }; const revision = { type: "integer", minimum: 0 };
route("get", "/api/health", "System", "Runtime health (does not claim service readiness)", true);
route("get", "/api/openapi.json", "System", "API specification", true);
route("get", "/api/auth/github", "Authentication", "Start GitHub OAuth", true);
route("get", "/api/auth/callback", "Authentication", "Fixed OAuth callback; verifies state and numeric user ID", true);
route("get", "/api/auth/session", "Authentication", "Current administrator and CSRF token");
route("post", "/api/auth/logout", "Authentication", "Revoke current session");
route("get", "/api/posts", "Content", "List private management records");
route("post", "/api/posts", "Content", "Create private draft", false, { source: string, slug: string, format: { enum: ["md", "mdx"] } }, ["source", "slug"]);
route("get", "/api/posts/{id}", "Content", "Read original source");
route("put", "/api/posts/{id}", "Content", "Save source with optimistic revision", false, { source: string, expectedRevision: revision }, ["source", "expectedRevision"]);
route("patch", "/api/posts/{id}", "Content", "Patch supported front matter preserving unknown bytes", false, { metadata: { type: "object" }, expectedRevision: revision }, ["metadata", "expectedRevision"]);
route("get", "/api/posts/{id}/history", "Content", "List versions");
route("post", "/api/posts/{id}/restore", "Content", "Restore as a new draft preserving current saved version", false, { versionId: string, expectedRevision: revision }, ["versionId", "expectedRevision"]);
route("post", "/api/import", "Content", "Import repository baseline once without publishing");
for (const kind of ["settings", "navigation", "icons"]) {
	route("get", `/api/${kind}`, "Settings", `Read ${kind}`);
	route("put", `/api/${kind}`, "Settings", `Save private ${kind} revision`, false, { data: { type: "object" }, expectedRevision: revision }, ["data", "expectedRevision"]);
}
route("get", "/api/media", "Media", "List private media metadata");
route("post", "/api/media/intents", "Media", "Create constrained authenticated browser upload", false, { name: string, contentType: string, size: { type: "integer", maximum: 33554432 } }, ["name", "contentType", "size"]);
route("post", "/api/media/upload", "Media", "Blob SDK upload protocol; token requests authenticate, callbacks verify provider signature", true, { type: string, payload: { type: "object" } }, ["type", "payload"]);
route("get", "/api/media/{id}/content", "Media", "Authenticated private media bytes");
route("post", "/api/media/import", "Media", "Import direct HTTPS image from configured host allowlist", false, { url: string, alt: string, caption: string }, ["url"]);
route("patch", "/api/media/{id}", "Media", "Save alternative text and caption independently", false, { alt: string, caption: string });
route("delete", "/api/media/{id}", "Media", "Tombstone private media; retain immutable historical versions");
route("get", "/api/public/comments", "Public interactions", "Read visible comments and deleted reply placeholders", true);
route("post", "/api/public/comments", "Public interactions", "Post plain text after Turnstile, origin, ban and rate checks", true, { articleId: string, parentId: string, name: string, email: string, body: string, turnstileToken: string }, ["articleId", "name", "body", "turnstileToken"]);
route("get", "/api/public/friends", "Public interactions", "Read last verified public friend snapshot", true);
route("post", "/api/public/friends", "Public interactions", "Submit friend application", true, { name: string, url: string, description: string, avatar: string, email: string, turnstileToken: string }, ["name", "url", "email", "turnstileToken"]);
for (const resource of ["comments", "bans", "friends", "mail"]) route("get", `/api/${resource}`, "Moderation", `List private ${resource} records`);
route("post", "/api/comments/{id}/delete", "Moderation", "Soft-delete comment preserving reply relationships");
route("post", "/api/bans", "Moderation", "Ban stable visitor subject", false, { subject: string, reason: string }, ["subject"]);
route("delete", "/api/bans/{id}", "Moderation", "Unban visitor");
route("post", "/api/friends/{id}/approve", "Moderation", "Approve for next explicit release");
route("post", "/api/friends/{id}/reject", "Moderation", "Reject transactionally and enqueue unique notification", false, { reason: string }, ["reason"]);
route("patch", "/api/friends/{id}", "Moderation", "Save grouping and order for next release", false, { group: string, sortOrder: { type: "integer" } });
route("post", "/api/mail/{id}/reconcile", "Mail", "Reconcile uncertain send; never blindly resend", false, { providerId: string });
route("post", "/api/webhooks/resend", "Mail", "Receive signed Resend delivery events", true);
route("post", "/api/releases", "Publishing", "Freeze explicit selection and return durable task", false, { postIds: { type: "array", items: string }, expectedRevisions: { type: "object", additionalProperties: revision }, idempotencyKey: string }, ["postIds", "expectedRevisions", "idempotencyKey"]);
route("get", "/api/tasks", "Publishing", "Read durable deployment and maintenance tasks");
route("get", "/api/tasks/{id}", "Publishing", "Read task evidence and conflict details");
route("post", "/api/tasks/{id}/reconcile", "Publishing", "Resume or reconcile task without duplicate uncertain commit");
route("get", "/api/maintenance/backups", "Maintenance", "List verified private backups");
route("post", "/api/maintenance/backup", "Maintenance", "Create durable private backup task");
route("post", "/api/maintenance/restore", "Maintenance", "Validate in isolated database and restore with write guard", false, { backupId: string, confirm: { const: true } }, ["backupId", "confirm"]);
route("post", "/api/maintenance/check", "Maintenance", "Read deployment counts and theme release information");
route("get", "/api/maintenance/cron", "Maintenance", "Authenticated daily checks and backup", true);
paths["/api/maintenance/cron"].get.security = [{ cron: [] }];
export const openApiDocument = { openapi: "3.1.0", info: { title: "Nocticur management API", version: "0.1.0" }, servers: [{ url: "https://admin.mourn.top" }], paths, components: { securitySchemes: { session: { type: "apiKey", in: "cookie", name: "__Host-admin-session" }, csrf: { type: "apiKey", in: "header", name: "x-csrf-token", description: "Required for writes together with same management Origin; GET requires session only" }, cron: { type: "http", scheme: "bearer" } } } };
